package jkea.util.data.template;

import jkea.core.Simulator;

/**
 * An interface defining a leakage point generated by a {@link Simulator}
 */
public interface Template {

	/**
	 * For a given transition value, output the leakage.
	 *
	 * @param transition
	 *            the transition value
	 * @return the leakage value
	 */
	public double leak(short transition);

	/**
	 * For a given leakage value and transition, calculate the density of the
	 * leakage.
	 *
	 * @param leak
	 *            the leakage value
	 * @param transition
	 *            the transition value
	 * @return the density of the leakage
	 */
	double leakDensity(double leak, short transition);
}
